name: Pylint

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (setup.py, pyproject.toml, or requirements.txt)
      run: |
        python -m pip install --upgrade pip
        if [ -f setup.py ]; then
          pip install .
        elif [ -f pyproject.toml ]; then
          pip install .
        elif [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No recognized dependency file found!" && exit 1
        fi
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
