# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates Python Static Analyzer (Pysa) with
# GitHub's Code Scanning feature.
#
# Python Static Analyzer (Pysa) is a security-focused static
# analysis tool that tracks flows of data from where they
# originate to where they terminate in a dangerous location.
#
# See https://pyre-check.org/docs/pysa-basics/

name: Pysa

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '42 0 * * 6'

permissions:
    contents: read

jobs:
  pysa:
    permissions:
      actions: read
      contents: read
      security-events: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyre-check
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pysa
        run: |
          # Create .pyre directory if it doesn't exist
          mkdir -p .pyre
          
          # Run Pysa analysis
          pyre analyze --save-results-to pysa-results.json || true
          
          # Convert results to SARIF format
          pyre-safe-report report pysa-results.json --format sarif > pysa-results.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pysa-results.sarif
          category: pysa

      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pysa-results
          path: |
            .pyre/
            pysa-results.json
            pysa-results.sarif
          retention-days: 5
